#!/bin/bash

readargs() {
  while [ "$#" -gt 0 ] ; do
    case "$1" in
       -c)
        if [ "$2" ] ; then
          commit="$2"
          shift ; shift
        else
          echo "Missing a value for $1."
          echo
          shift
          usage
exit
        fi
      ;;
      *)
        echo "Unknown option or argument $1."
        echo
        shift
        usage
      exit
      ;;
    esac
  done
}

#  BEGIN THE PROGRAM
readargs "$@"
shortcommit=$( echo ${commit} | cut -c 1-7)
name=obs-studio

rm -rf ${name}-${shortcommit}/
rm -f ${name}-${shortcommit}.tar.gz
#--depth 1
git clone https://github.com/obsproject/obs-studio.git ${name}-${shortcommit}
pushd ${name}-${shortcommit}
git init
#git fetch origin "${commit}"
git checkout --force "${commit}" 
echo "You are in Commit: $( git rev-parse HEAD )"
popd
pushd ${name}-${shortcommit}/plugins
git submodule init && git submodule update
popd
pushd ${name}-${shortcommit}/plugins/obs-outputs
git submodule init && git submodule update
popd
pushd ${name}-${shortcommit}/plugins/obs-outputs/ftl-sdk
git submodule init && git submodule update
popd
tar -cvzf ${name}-${shortcommit}.tar.gz ${name}-${shortcommit}
echo "You are in Commit: $( git rev-parse HEAD )"
