#!/bin/bash

readargs() {
  while [ "$#" -gt 0 ] ; do
    case "$1" in
       -c)
        if [ "$2" ] ; then
          commit="$2"
          shift ; shift
        else
          echo "Missing a value for $1."
          echo
          shift
          usage
exit
        fi
      ;;
      *)
        echo "Unknown option or argument $1."
        echo
        shift
        usage
      exit
      ;;
    esac
  done
}

#  BEGIN THE PROGRAM
readargs "$@"
shortcommit=$( echo ${commit} | cut -c 1-7)
name=obs-StreamFX

rm -rf ${name}-${shortcommit}/
rm -f ${name}-${shortcommit}.tar.gz
git clone --depth 1 https://github.com/Xaymar/obs-StreamFX.git ${name}-${shortcommit}
pushd ${name}-${shortcommit}
git checkout --force "${commit}" 
echo "You are in Commit: $( git rev-parse HEAD )"
popd
pushd ${name}-${shortcommit}/third-party
git submodule init && git submodule update
popd
pushd ${name}-${shortcommit}/cmake
git submodule init && git submodule update
popd
tar -cvzf ${name}-${shortcommit}.tar.gz ${name}-${shortcommit}

